-- 0001_initial.sql
-- Awakened v2.1 Phase B initial schema.
--
-- Tables:
--   users                  — one row per Sign-in-with-Apple identity
--   leaderboard_snapshots  — per-(user, metric) current + best value
--
-- Indexes:
--   idx_users_apple_sub          — UNIQUE; supports per-sub lookup
--                                  on every /v1/auth/verify call
--   idx_users_alias_lower        — UNIQUE on LOWER(alias);
--                                  case-insensitive alias collision
--                                  detection per BACKEND.md §13
--   idx_leaderboard_metric_value — non-unique; supports the top-N
--                                  ORDER BY current_value DESC query
--                                  used by GET /v1/leaderboard/top
--
-- Apply to remote (Cloudflare-side) D1:
--   wrangler d1 execute awakened-db --remote \
--     --file=migrations/0001_initial.sql
--
-- Local dry-run (Wrangler local D1 simulator):
--   wrangler d1 execute awakened-db --local \
--     --file=migrations/0001_initial.sql
--
-- Migration discipline: NEVER edit this file after applying to
-- remote. Add a new numbered file (0002_*.sql, 0003_*.sql) for
-- subsequent schema changes.

-- ── users ───────────────────────────────────────────────────────
-- Primary key is an internal UUID v4 (generated by Worker via
-- crypto.randomUUID()) rather than Apple's `sub` so the schema
-- stays portable if we ever add non-Apple auth providers
-- (Google, email, etc.) in v2.x+. apple_sub is a UNIQUE NOT NULL
-- foreign-key-style column that enables fast lookup by Apple
-- identity.
--
-- Timestamps are Unix epoch milliseconds (Worker uses Date.now()
-- which returns ms). Stored as INTEGER for sort-friendliness.
CREATE TABLE users (
  id         TEXT PRIMARY KEY,
  apple_sub  TEXT UNIQUE NOT NULL,
  alias      TEXT NOT NULL,
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL
);

-- ── leaderboard_snapshots ───────────────────────────────────────
-- One row per (user, metric) pair. v2.1 metrics:
--   'step_total'       — last-7-day cumulative step count
--   'sleep_streak'     — consecutive nights ≥7h sleep
--   'bedtime_streak'   — consecutive nights bedtime <00:00 local
--
-- current_value reflects the user's latest submitted value.
-- best_value is the all-time max ever submitted (computed at
-- UPSERT time via MAX(existing_best, new_current)). Used for
-- "personal record" surfaces in client.
--
-- ON DELETE CASCADE on the FK so /v1/account/delete cleanly
-- removes a user's leaderboard rows in one transaction.
CREATE TABLE leaderboard_snapshots (
  user_id       TEXT NOT NULL,
  metric        TEXT NOT NULL,
  current_value INTEGER NOT NULL,
  best_value    INTEGER NOT NULL,
  updated_at    INTEGER NOT NULL,
  PRIMARY KEY (user_id, metric),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- ── Indexes ─────────────────────────────────────────────────────
-- apple_sub uniqueness is enforced by the column constraint above,
-- but we add an explicit index here for query-planner clarity and
-- to mirror the alias-lower index pattern.
CREATE UNIQUE INDEX idx_users_apple_sub
  ON users (apple_sub);

-- Case-insensitive alias uniqueness. "TopDog" and "topdog" and
-- "TOPDOG" all collide. Per BACKEND.md §13: collision is rejected
-- with 409 ALIAS_TAKEN + server-generated suggestions, not
-- last-write-wins or auto-suffix.
CREATE UNIQUE INDEX idx_users_alias_lower
  ON users (LOWER(alias));

-- Composite index supporting the top-N leaderboard query:
--   SELECT ... FROM leaderboard_snapshots WHERE metric = ?
--     ORDER BY current_value DESC LIMIT ?
-- D1 can satisfy this with an index range scan (no full-table
-- sort) since current_value is the second sort key on disk.
CREATE INDEX idx_leaderboard_metric_value
  ON leaderboard_snapshots (metric, current_value DESC);
